### ISSUE TITLE
Size is too large and compile time of the docker is too long 

### ISSUE THREAD

**Issue by mysablehats** [opensimrt-ros/docker-opensimrt#8]
This is an issue because we cannot test the build process with github actions and jenkins and stuff. 

One idea I had to fix this would be to divide it into layers and build them separately,  picking the artefacts we need.

**Comment by frederico-klein** [comment]
I have added the CI thing. The image continues to be very large and it is still based on opensim 4.1 (see #11), but this all I can do for now.
